# this is a generated file, to avoid over-writing it just delete this comment
require 'jar_dependencies'

require_jar( 'io.netty', 'netty', '3.7.0.Final' )
require_jar( 'com.fasterxml.jackson.core', 'jackson-annotations', '2.4.0' )
require_jar( 'org.apache.commons', 'commons-compress', '1.4.1' )
require_jar( 'org.slf4j', 'slf4j-api', '1.6.4' )
require_jar( 'io.confluent', 'kafka-schema-registry-client', '1.0' )
require_jar( 'com.fasterxml.jackson.core', 'jackson-databind', '2.4.3' )
require_jar( 'org.slf4j', 'slf4j-log4j12', '1.6.1' )
require_jar( 'org.codehaus.jackson', 'jackson-mapper-asl', '1.9.13' )
require_jar( 'org.apache.kafka', 'kafka_2.10', '0.8.2.1' )
require_jar( 'com.thoughtworks.paranamer', 'paranamer', '2.3' )
require_jar( 'org.codehaus.jackson', 'jackson-core-asl', '1.9.13' )
require_jar( 'org.scala-lang', 'scala-library', '2.10.4' )
require_jar( 'jline', 'jline', '0.9.94' )
require_jar( 'net.sf.jopt-simple', 'jopt-simple', '3.2' )
require_jar( 'com.fasterxml.jackson.core', 'jackson-core', '2.4.3' )
require_jar( 'junit', 'junit', '3.8.1' )
require_jar( 'com.yammer.metrics', 'metrics-core', '2.2.0' )
require_jar( 'org.apache.zookeeper', 'zookeeper', '3.4.6' )
require_jar( 'org.tukaani', 'xz', '1.0' )
require_jar( 'net.jpountz.lz4', 'lz4', '1.2.0' )
require_jar( 'org.xerial.snappy', 'snappy-java', '1.0.5' )
require_jar( 'log4j', 'log4j', '1.2.16' )
require_jar( 'org.apache.kafka', 'kafka-clients', '0.8.2.1' )
require_jar( 'org.apache.avro', 'avro', '1.7.7' )
require_jar( 'com.101tec', 'zkclient', '0.3' )
require_jar( 'io.confluent', 'kafka-avro-serializer', '1.0' )
